INSERT INTO LIBRARY (id, label, type, ADDRESS_NUMBER, ADDRESS_STREET, ADDRESS_POSTALCODE, ADDRESS_CITY, DIRECTOR_SURNAME, DIRECTOR_NAME)
VALUES ('1', 'Bibliothèque François Mitterand','PUBLIC',11, 'François Mauriac',75013, 'PARIS', 'Sylviane', 'Tarsot-Gillery');


INSERT INTO LIBRARY (id, label, type, ADDRESS_NUMBER, ADDRESS_STREET, ADDRESS_POSTALCODE, ADDRESS_CITY, DIRECTOR_SURNAME, DIRECTOR_NAME)
VALUES ('2', 'Bibliothèque l''Alcazar','PUBLIC',58, '''Cours Belsunce',13001, 'PARIS', 'Etienne', 'DEMOLINS');


INSERT INTO LIBRARY (id, label, type, ADDRESS_NUMBER, ADDRESS_STREET, ADDRESS_POSTALCODE, ADDRESS_CITY, DIRECTOR_SURNAME, DIRECTOR_NAME)
VALUES ('3', 'Bibliothèque Parmentier','PUBLIC',20, 'Avenue Parmentier',75011, 'PARIS', 'Emmanuel', 'Cuffini');


INSERT INTO LIBRARY (id, label, type, ADDRESS_NUMBER, ADDRESS_STREET, ADDRESS_POSTALCODE, ADDRESS_CITY, DIRECTOR_SURNAME, DIRECTOR_NAME)
VALUES ('4', 'Bibliothèque des Conservatoires de la Ville de Paris','PUBLIC',12, 'place carrée',75001, 'PARIS', 'François', 'DUPONT');

INSERT INTO LIBRARY (id, label, type, ADDRESS_NUMBER, ADDRESS_STREET, ADDRESS_POSTALCODE, ADDRESS_CITY, DIRECTOR_SURNAME, DIRECTOR_NAME)
VALUES ('5', 'Bibliothèque Charlotte Delbo','PUBLIC',2, 'Passage des petits frères',75002, 'PARIS', 'Marc', 'Raignier');

INSERT INTO LIBRARY (id, label, type, ADDRESS_NUMBER, ADDRESS_STREET, ADDRESS_POSTALCODE, ADDRESS_CITY, DIRECTOR_SURNAME, DIRECTOR_NAME)
VALUES ('6', 'Bibliothèque Médiathèque Marguerite Audoux','PUBLIC',10, 'rue Portefoin',75003, 'PARIS', 'Stephane', 'RUFFION');

INSERT INTO LIBRARY (id, label, type, ADDRESS_NUMBER, ADDRESS_STREET, ADDRESS_POSTALCODE, ADDRESS_CITY, DIRECTOR_SURNAME, DIRECTOR_NAME)
VALUES ('7', 'Bibliothèque Arthur Rimbaud','PUBLIC',2, 'place Baudoyer',75004, 'PARIS', 'Cyrille', 'HOUILLON');
